### ISSUE TITLE
Add "id" as an option?

### ISSUE THREAD

**Issue by KJohnson74** [nescalante/knockout.contextmenu#11]
Context menu works great. However there is no easy way to add an "id" to the context menu item, and for my use case this would be rather helpful.

**Comment by nescalante** [comment]
Which would be the use case?

**Comment by KJohnson74** [comment]
I'm also working with dropzone.js and to create an instance of dropzone programmatically an "id" needs to be present on the DOM element to find where it should be created, and I only want to add it to one of the context menu items.

**Comment by nescalante** [comment]
adding an id won't work for you since the menu item elements are being created and destroyed everytime you open and close the menu. You are free to open a pull request to add "ids" as an option, but I am afraid that won't solve your problem. A workaround for this would be to listen the event that opens the menu and then do the bind with dropzone after the menu is opened

**Comment by KJohnson74** [comment]
Ok I'll make a pull request to add that. Also, that is what I'm trying to do. I'm just unsure which event I would be listening for. The context menu has to have the elements all there for dropzone to be able to bind to it. So like you said after it's created.
